version: '3.7'

services:
  flask:
    build: ./backend
    container_name: flask
    restart: always
    expose:
      - 5001

  nginx:
    build: ./frontend
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
